name: test_assignment
channels:
  - conda-forge
  - defaults
dependencies:
  - nbconvert=6.4.5
  - python=3.10.2
  - ipython=8.1.1
  - numpy=1.22.2
  - matplotlib=3.5.1
  - pandas=1.4.1
  - scipy=1.8.0
  - imageio>=2.5.0
  - imageio-ffmpeg
  - colorcet
  - cmocean
  - tqdm
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - hypothesis>=5.8.0
  - pip
  - trimesh
  - rtree
  - pyembree
  - panel
  - ipygany
  - ipyvtklink
  - pythreejs
  - pooch
  - pip:
      - pytest-memprof
      - trame>=2.2.6
      - trame-client>=2.4.2
      - trame-server>=2.8.0
      - trame-vtk>=2.0.17
